[F] Build EntityGroup component
ManifoldScholar/manifold pull request #3117
Opened 2021-11-10 16:42 UTC by 1aurend

2021-11-11 15:11 UTC, 1aurend commented on client/src/global/components/atomic/EntityBox/styles.js
> +  --entity-box-padding-right: 30px;
Made these into vars for styling the `EntityGroup` header.

2021-11-12 19:16 UTC, dananjohnson requested changes
Looking good, @1aurend. Let me know if you have any questions about my feedback. One more thing to note is that it looks like EntityBox has more inline padding in the comps.

Here's design:
<img width="1158" alt="Screen Shot 2021-11-12 at 11 13 28 AM" src="https://user-images.githubusercontent.com/12454203/141522476-caa406f1-89bc-459d-805e-af10ab9e20a4.png">

And here's the implementation:
<img width="1047" alt="Screen Shot 2021-11-12 at 11 12 22 AM" src="https://user-images.githubusercontent.com/12454203/141522463-276d853a-2899-4d0b-9634-f6dbaea27bf1.png">

2021-11-12 19:16 UTC, dananjohnson commented on client/src/global/components/composed/ThumbnailGrid/styles.js
> +        : null;
I find this kind of thing really hard to read. (eslint doesn't like it apparently either. 🙂) Is there another way you could write it? (Not saying the way I did is right.  The logic seems more if/elseif than mine.)

2021-11-15 18:32 UTC, dananjohnson requested changes
Great work, @1aurend! I think the responsive styles just need a bit of attention. See my comments below.

2021-11-15 18:32 UTC, dananjohnson commented on client/src/global/components/composed/EntityGroup/index.js
> +    >
Using `style` should be a last resort, meaning we shouldn't build it into `EntityGroup`. The reason is that styles inlined in HTML have highest specificity, so couldn't be overridden by any other styled components (except by using `!important`). If you want to pass CSS var values to EntityBox, I think you should expose `className` as a prop on EntityBox and use it as a styled component in EntityGroup.

2021-11-15 18:32 UTC, dananjohnson commented on client/src/global/components/composed/EntityGroup/index.js
> +        "--EntityBox-Background-padding-inline": "60px"
Are the last two needed? They have the same values as EntityBox.

2021-11-15 18:32 UTC, dananjohnson commented on client/src/global/components/atomic/EntityBox/styles.js
> +  padding-inline: var(--EntityBox-Background-padding-inline, 60px);
A couple changes with this:
* I measured this value in the comps as 72px, not 60px.
* On mobile, it's too wide. Have it match the inline padding of the project grid above it, scaling between desktop and mobile with `fluidScale`.
<img width="389" alt="Screen Shot 2021-11-15 at 10 12 54 AM" src="https://user-images.githubusercontent.com/12454203/141833689-29ff283c-b608-4b84-869a-2d28d1ec57bf.png">

2021-11-15 18:32 UTC, dananjohnson commented on client/src/global/components/composed/EntityGroup/styles.js
> +  color: var(--strong-color);
Not essential, but if you define this on `GroupHeader` you only have to do it once. The icon and HeaderText will just inherit it.

2021-11-15 18:32 UTC, dananjohnson commented on client/src/frontend/containers/Test/index.js
> +          />
This component has a really nice, simple set of props!

2021-11-15 18:32 UTC, dananjohnson commented on client/src/global/components/composed/EntityGroup/styles.js
>    box-sizing: content-box;
Nice solution here!

2021-11-16 01:22 UTC, dananjohnson approved these changes
Looks good! 👏🏻  Go ahead and merge.

2021-11-16 01:22 UTC, dananjohnson commented on client/src/global/components/atomic/EntityBox/styles.js
> +  --EntityBox-Background-padding-inline: ${fluidScale("72px", "20px")};
Prob simpler to add these values as defaults when you use the vars below rather than define them here.

2021-11-16 17:12 UTC, merged