[C] Refactor FE containers
ManifoldScholar/manifold pull request #3306
Opened 2022-03-31 20:58 UTC by 1aurend

2022-04-26 18:28 UTC, 1aurend commented
@dananjohnson here are the FE containers minus `ResourceDetail` and `ResourceCollectionDetail`. There's one test that I can't get. For some reason, the `ProjectResources` container doesn't seem to mount the same way as the others. Do you mind taking a look before I spend more time on it?

2022-04-28 20:36 UTC, dananjohnson requested changes
Great work, @1aurend! Just noticed one issue: something's up with the Resources container. I can navigate tot= that route client-side, but if I try to load the URL directly there's a 500 error. Check that out and the little prop-type warning below. Otherwise this looks good to go!

2022-04-28 20:36 UTC, dananjohnson commented on client/src/frontend/containers/EventList/index.js
> +  journalBreadcrumbs: PropTypes.object
Seeing a prop-type warning for this one:
```
Failed prop type: Invalid prop `journalBreadcrumbs` of type `array` supplied to `Frontend.Containers.EventList`, expected `object`.
```

2022-04-29 20:00 UTC, 1aurend commented
@dananjohnson turns out I was missing an import null guard in the resources container. When you navigate via the project, the project is already fetched by the wrapper but not when loading the page directly. Thanks for the catch!

2022-05-20 14:18 UTC, zdavis commented
@1aurend, as far as you're concerned, is this good to go?

2022-05-20 15:16 UTC, 1aurend commented
> @1aurend, as far as you're concerned, is this good to go?

It's ready except for these markup warnings that I couldn't figure out how to solve:
<img width="685" alt="Screen Shot 2022-05-04 at 9 01 49 AM" src="https://user-images.githubusercontent.com/32903719/169559001-ff460c58-e45c-458e-8bce-ff15ba212732.png">

2022-05-20 20:53 UTC, zdavis commented
Ok, I'll see if I can figure out the warning.

2022-05-23 17:22 UTC, dananjohnson commented
@1aurend when I pulled this down to take a look at it again, I noticed exceptions when visiting the resources page for a project that doesn't have any resources. Interestingly I didn't notice the server warning you mentioned above with resource collections. The placeholder for that page seems to render without issue. Do you want to take a look at the resources error? If there's not an easy fix or you don't have time, then just open up a new PR with the FatalError fix and we'll merge that in separately for v7.

2022-05-25 00:06 UTC, dananjohnson approved these changes

2022-05-25 00:24 UTC, merged