[WIP][F] Add support for MathML
ManifoldScholar/manifold pull request #3530
Opened 2023-01-04 20:43 UTC by 1aurend

2023-01-09 18:31 UTC, 1aurend commented
@dananjohnson No rush, but I'm hoping you can give this an a11y review when you get a chance. I made some progress applying annotation styles to math elements and replacing their content in annotation lists. However, in addition to the things we've already discussed, I've noticed a couple of possible issues with keyboard support:
- If we add the same interactive attributes / onClick to the math part of the highlight as to the surrounding text spans, there are keyboard controls for the span and then keyboard controls for its mjx element child, if accessibility is turned on. This might be fine, but it took me a second to figure out. Are the aria attributes correct and clear enough here?
  <img width="637" alt="Screen Shot 2023-01-09 at 10 19 52 AM" src="https://user-images.githubusercontent.com/32903719/211379890-bc36899c-7c40-49c9-b444-949d2ee9dabb.png">
  Pressing `enter` here on the span opens the annotation drawer:
  <img width="225" alt="Screen Shot 2023-01-09 at 10 25 43 AM" src="https://user-images.githubusercontent.com/32903719/211380525-68215ccc-b857-4e7b-b0d6-11cf97ea120b.png">
  Pressing `enter` here on the mjx element opens the MathJax explorer:
  <img width="249" alt="Screen Shot 2023-01-09 at 10 23 30 AM" src="https://user-images.githubusercontent.com/32903719/211380269-7b65d041-6c1b-4ffd-a7fc-2f4d2761215d.png">

- It takes a number of presses of tab to tab through a math element because of tabbable internal elements MathJax creates. However, there are no associated focus styles, so it's hard to tell where you are.

Also, not a11y, but selecting sentences or paragraphs that contain math seems to work in Chrome/Safari, even though the math does not appear selected. It's buggy, however, in FF. FF seems to not accurately select text characters following the math elements. Can we improve this?

2023-02-08 22:13 UTC, 1aurend commented
Note to self: remove MathJax deps before merging if we decide to ahead without it.

2023-02-17 18:32 UTC, dananjohnson requested changes
@1aurend super cool feature! Great work on this. I just reviewed the code, as we've walked through it together and it appears to work as expected in the application. If there's any browser or a11y testing you'd like me to do though, let me know.

2023-02-17 18:32 UTC, dananjohnson commented on client/src/reader/components/section/body-nodes/nodes/Math/Node.js
> +  const wrapperStyles = Wrapper === "div" ? { width: "max-content" } : {};
You may want to add `{ maxWidth: "100%" }`. `width: max-content` will cause an element to ignore the width of its parent and extend right off the page if it's really that wide.

2023-02-17 18:32 UTC, dananjohnson commented on client/src/theme/assets/fonts/FiraMath/mathfonts.css
> +}
It doesn't look like this file is being used anywhere.

2023-02-22 18:34 UTC, dananjohnson approved these changes
APPROVED!

2023-02-22 19:00 UTC, merged