[F] WebVTT support
ManifoldScholar/manifold pull request #3794
Opened 2024-12-19 19:32 UTC by 1aurend

2024-12-19 19:39 UTC, scryptmouse commented
I can't really say. If it's easy, we should support as many as makes sense. If it's hard to model or expose it in the UI, I think it depends on how likely it is folks are going to need multiple tracks.

2024-12-19 19:43 UTC, dananjohnson commented
Yeah. I think the known use case we have is for a single track. Support for multiple sounds good, but only if it's not too difficult to do. On the frontend, I guess we'd check for a track in the currently set language and fall back to "en"?

We should upgrade the package, but lets put a pin in it and revisit when we work on dependency upgrades next quarter.

2024-12-19 19:51 UTC, 1aurend commented
Sound good re: package upgrade.

And probably makes sense to wait on multiple languages/tracks until we have a use case. The video player package displays a dropdown list of languages so the users can choose which to show, if it's supplied with more than one text track of `kind="captions"`. So, that part could be pretty trivial. As for modeling it, we could do something like what we did with `alt_text` to associate a `text_track_lang` and/or `text_track_kind` field with the relevant attachment. Anyhow... thoughts for if we get there.

2025-01-09 20:56 UTC, dananjohnson requested changes
Working well! Just noted a couple minor things. The FE part of this is good to go once addressed, as far as I'm concerned.

2025-01-09 20:56 UTC, dananjohnson commented on client/src/backend/components/resource/form/kind/Video/Video.styles.js
I think a lot of the styles here can be dropped. They override other styles that seem to work perfectly fine. I would keep the flexbox properties for the Group div, however, and replace the `inline-size` property on the child selector with `flex-basis: 350px`. This should yield something like this, which removes the wide gap between the children on desktop and makes the upload fields more consistent on mobile with how they look for other resource types.

<img width="850" alt="Screenshot 2025-01-09 at 12 33 42 PM" src="https://github.com/user-attachments/assets/8da034c6-4711-4f46-b6f6-67099ba7a0b5" />
<img width="374" alt="Screenshot 2025-01-09 at 12 33 56 PM" src="https://github.com/user-attachments/assets/3108255b-d469-4ea9-a201-c715c2f587a5" />

2025-01-09 20:56 UTC, dananjohnson commented on client/src/frontend/components/resource-player/Video/index.js
> +        : captionsTrackUrl;
I know it's just for dev, but string replacing like this seems liable to alter some urls that we don't want to alter. Could you use the URL interface here and change the `port` property instead?

2025-01-09 20:56 UTC, dananjohnson commented on client/src/frontend/components/resource-player/Video/index.js
> +      });
What is this for? Might be good to add a comment for future developers.

2025-01-13 17:07 UTC, 1aurend commented on client/src/frontend/components/resource-player/Video/index.js
> +      });
Is your question rhetorical? If it isn't, that moves the captions up from their default position, so the controls overlay doesn't cover them. I didn't know before I looked into this that they can't be positioned with css.

2025-01-13 17:27 UTC, dananjohnson commented on client/src/frontend/components/resource-player/Video/index.js
> +      });
It is! I mean, I didn't know that, but I don't think others will either, so a brief comment in your code would be good.

2025-01-13 17:35 UTC, 1aurend commented on client/src/frontend/components/resource-player/Video/index.js
> +      });
Yeah, kind of interesting. `::cue` accepts only a limited set of css properties: https://developer.mozilla.org/en-US/docs/Web/CSS/::cue

2025-01-13 17:59 UTC, 1aurend commented on client/src/backend/components/resource/form/kind/Video/Video.styles.js
I agree— I don't love what I did with the styles here, but issue I was trying to solve was this. When the uploaded files have different length filenames the inputs can be different heights:
<img width="926" alt="Screenshot 2025-01-13 at 9 56 50 AM" src="https://github.com/user-attachments/assets/e5377daf-f66d-43ea-a658-053304e9109e" />
I replaced `inline-size` with `flex-basis`. That seems cleaner, but what do you think about leaving the other child styles to address the differing heights?

2025-01-13 18:16 UTC, dananjohnson commented on client/src/backend/components/resource/form/kind/Video/Video.styles.js
Makes sense! That's fine.

2025-01-14 01:30 UTC, 1aurend commented
@dananjohnson can you unblock merging whenever you get a moment? Thanks!

2025-01-14 17:11 UTC, dananjohnson approved these changes

2025-01-15 16:27 UTC, merged